### ISSUE TITLE
App Crash - Could not load GLCalendarDayCell

### ISSUE THREAD

**Issue by harryblam** [Glow-Inc/GLCalendarView#36]
Seeing a crash after installing through cocoapods v1.0.3 on iOS 10.2 simulator.

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </Users/....app> (loaded)' with name 'GLCalendarDayCell''

**Comment by gunhansancar** [comment]
Hey i got the same error and solved by updating the version to

pod 'GLCalendarView', '~> 1.2.1'

**Comment by RishabhTayal** [comment]
I am still seeing this error in version 1.2.1. Any one else?

**Comment by Pulkit2017** [comment]
It did not resolve my issue by update to 1.2.1 . 
xcode 11.3.1
Got to pods->GLCalendarView->Resources->GLCalendarView.xib->Open File inspector on the inspector-> Target Membership-> make sure to tick all
